### ISSUE TITLE
gitlab: commit notification should only include title

### ISSUE THREAD

**Issue by blocktrron** [fleaz/CptHook#57]
Currently the notification generated from a new commit includes the full commit message. This is not ideal for a quick notification.

Instead, I think it would be better to only use the commit title for notification purposes.

![](https://i.imgur.com/PST5cZP.png)

**Comment by herbetom** [comment]
This line seems relevant: https://github.com/fleaz/CptHook/blob/master/input/gitlab.go#L138

**Comment by fleaz** [comment]
@herbetom That's indeed the template which gets used for the commit message but you can't call arbitrary functions like e.g. split in a template.

The two options I see are either a custom template function like `firstLine`  which we then can call in the template or we tackle this in line 411 and split the commit message before loading the data into the template.

**Comment by herbetom** [comment]
I only looked for maybe 30s for that line. My "idea" was that you could insert instead of `Message` something diffrent. But since `Message` isn't used somewhere else i would rename `Message` in 138 to title and split it in 411 (and also rename it). Or just add another line around 411 for the title and keep Message arround for the future.

**Comment by fleaz** [comment]
Fixed in #60
